### ISSUE TITLE
Permission issue in h: (home drive)

### ISSUE THREAD

**Issue by poornic** [savishy/vagrant-boxes#20]
I have faced below error  , while creating a dir in my homedrive (h:)

```
Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': No such file or directory @ dir_s_mkdir - H: (Errno::ENOENT)
```

This issue resolved by changing the homedrive to any accessible path (c:\users\xxxx)

**Comment by savishy** [comment]
This issue is because on the system under consideration, `$HOMEDRIVE` and/or `$HOMEPATH` were not set. However, `$USERPROFILE` is correctly set to `C:\Users\USER_NAME`. 

Since on most systems `$HOMEDRIVE/$HOMEPATH` is present, going with this change. Local modifications can be made as per the situation on the target system.
